#数据库配置
spring:
  resources:
    add-mappings: true
  datasource:
    druid:
      mysql:
        usePingMethod: false
      # 主库数据源
      master:
        url: jdbc:mysql://127.0.0.1:3306/conandb?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 'root'
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:

      url: jdbc:mysql://127.0.0.1:3306/conandb?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
      password: QQpMB7nTrCTmJea0CGiyvsBk+DYcsjxO+qo/1nXu3WDj+sDU1ESgTJrArtGdGyYR3xA/0aCHD5gX3NmnH7pWUw==
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJvs3mvN6MBUwK8V7ZdSndPMvw4rKPK/e4uJAWhsFydZXsEr5MsummUhS3TjqYHYbsm1Gc0T8j3jdNmj3qlREQkCAwEAAQ==


  redis:
    # 地址
    host: 172.16.70.20
    # 端口，默认为6379
    port: 6379
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

  kafka:
    bootstrap-servers: 172.16.70.43:9092
    consumer:
      group-id: conan-agent-js
  data:
    elasticsearch:
      #      cluster-name: elasticsearch
      #      cluster-nodes: 10.90.71.138:9300
      # cluster-name: xes_log_cluster_test
      # cluster-nodes: 10.90.71.158:9300,10.90.71.166:9300,10.90.71.44:9300
      cluster-name: xes_log_cluster_wg
      cluster-nodes: 172.16.70.43:9300
  jackson:
    time-zone: Asia/Shanghai    #或UTC
system:
  env: TEST
  redis:
    cacheTime: 14 # 录制redis数据的过期时间为14天  14*24*60*60 S

